### ISSUE TITLE
PasswordChangeAssistant usage in Linux

### ISSUE THREAD

**Issue by aashrithh** [Rookiestyle/PasswordChangeAssistant#16]
Hello,
Do you support usage of PasswordChangeAssistant on Linux?
I'm using Ubuntu 22.04 with mono-complete. I'm trying to auto-type from the password change assistant window but it doesn't autotype.
I have created a system wide hotkey based on https://keepass.info/help/v2/setup.html#mono and it's able to successfully call up the global auto type window.

**Comment by Rookiestyle** [comment]
Using the *Copy* buttons should work already today.
Using Auto-Type will be tricky one and cannot be solved without any user interaction at all unfortunaately.

On my Ubuntu VM this approach was successful:
1. Install the [KPUInput plugin](https://keepass.info/help/kb/autotype_wayland.html)
2. Add a *{DELAY 10000}* at the beginning of the password that is to be typed
3. Klick "Auto-Type"
4. Activate the target window
5. Navigate to the field that is to be typed into


If you're already able to successfully execute *Perform Auto-Type* from the entry's context, you might be able to skip the first step.

Without KPUInput I could not perform any auto-type (beside using the Global Auto-Type hotkey which is not helpful here)
With KPUInput *Perform Auto-Type* worked.
As it did not work from my plugin's screen I suppose the plugin does not expect a dialog window to be opened within KeePass. Due to that, I recommend to test by preceeding a delay. 10 seconds should be sufficient time to click Auto-Type, activate the target window and place the cursor in the first field.

If this works for you, I can automate the *DELAY* part (step #2) in th next release of my plugin.

![image](https://user-images.githubusercontent.com/36454520/196049578-40f26518-3dfb-4a14-a23e-b0b49b72a277.png)

**Comment by aashrithh** [comment]
Thank you very much for looking into this.
I installed the KPUInput Plugin and tried it but I face a interesting issue. 
The case of the letters being typed is getting inverted from what is there in the password. Please see case 1 & 2 in the attached document.

**Comment by Rookiestyle** [comment]
Just to check:

Before you installed KPUInput, *Perform Auto-Type* in KeePass and in my plugin did not work?
After you installed KPUInput, *Perform Auto-Type* in KeePass and in my plugin works?
*Perform Auto-Type* in KeePass does not invert the case of letters, this only happens in my plugin?

**Comment by aashrithh** [comment]
_Before you installed KPUInput, Perform Auto-Type in KeePass and in my plugin did not work?_ -- No, Auto type in Keepass worked but not in the plugin

_After you installed KPUInput, Perform Auto-Type in KeePass and in my plugin works?_ - Yes

 _Perform Auto-Type in KeePass does not invert the case of letters, this only happens in my plugin?_ - Yes.

**Comment by aashrithh** [comment]
39237617
W.$8}1u\q_>f&|e

**Comment by Rookiestyle** [comment]
That's weird. 
Without KPUInput I can not use *Perform Auto-Type* but can only use the global Auto-Type hotkey.
With KPUInput I can do all and no inverted upper / lower case is happening.

I'll check deeper but for expectation management purpose... If I'm not able to reproduce this, it won't be possible to fix it.

**Comment by aashrithh** [comment]
_Without KPUInput I can not use Perform Auto-Type but can only use the global Auto-Type hotkey._  ---I thought you meant global auto-type hotkey when you said Perform Auto-Type in KeePass....Can you please send me a screenshot of which button you are referring to for 'Perform Auto-Type in Keepass'?

**Comment by Rookiestyle** [comment]
![image](https://user-images.githubusercontent.com/36454520/196241986-c8debea0-87c7-4410-ada0-425f9f9454cb.png)

**Comment by Rookiestyle** [comment]
When you try again, please use the attached version.
This version will delay auto-typing from within the Password Change Assistant window by 10 seconds. You don't need to manually add this delay.

As I still cannot reprode the upper / LOWER case thing, you might still face this issue.
If that is the case, please doublcheck: *Perform Auto-Type* (NOT: global auto-type)  in KeePass does not invert the case of letters, this only happens in my plugin?

[PasswordChangeAssistant.zip](https://github.com/Rookiestyle/PasswordChangeAssistant/files/9803434/PasswordChangeAssistant.zip)

**Comment by aashrithh** [comment]
I will try this today/tomorrow and report back.

**Comment by aashrithh** [comment]
I have some interesting things to report:-

1. Now, I'm able to auto type from using Perform Auto type in Keepass & Password Change Assistant without KPUInput :)
2. With the new PCA plugin in the above comment, the issue of case inversion is not happening for me. Is it possible to make the time delay input/configurable entry?

**Comment by Rookiestyle** [comment]
The attached version let's you change the Auto-Type delay in the plugin's options

On Unix it defaults to 10 seconds.
On WIndows it defaults to 0 seconds. 

[PasswordChangeAssistant.zip](https://github.com/Rookiestyle/PasswordChangeAssistant/files/9893778/PasswordChangeAssistant.zip)

**Comment by aashrithh** [comment]
Thank you.
