### ISSUE TITLE
Can PasswordChangeAssistant get enabled to work with SAP logon / KeeSAPLogon plugin ?

### ISSUE THREAD

**Issue by joergles** [Rookiestyle/PasswordChangeAssistant#19]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)
I am using SAP Logons a lot with Keepass. Would be handy to use Password Change Assistant too, but URL is requiring a CMD command like "cmd://"C:\Program Files (x86)\SAP\FrontEnd\SAPgui\sapshcut.exe" -sysid="DN2" -language=EN -client=100 -user={username} -pw={password}". Actually with this URL in the Update URL there is just nothing coming up after clicking "Change password".

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)
I think a lot of users use Keepass for SAP logon, so this would be a very helpful feature.

## Example
[NOTE]: # (Show a picture or a mock-up if applicable)

**Comment by Rookiestyle** [comment]
I don't use KeeSAPLogon as my company switched to passwordless login using Windows Hello for Business.

I tried to reproduce this at my private laptop.
When I define your command as URL, KeePass tries to open sapshcut.exe and since I don't have SAP installed on my private laptop the following is shown:
![image](https://user-images.githubusercontent.com/36454520/204613207-80c757dc-d8b8-419d-bfe7-ca8c6d163061.png)

Despite the rror message, KeePass obviously tries to start SAP.

There actually is an error thake makes the url to appear twice and I will fix that.

I'ld like to fix your issue as well.
You have above url set as url for the entry?
You click "Change password" in the entry's context menu, PasswordChangeAssistant is shown and nothing else happens?
If you do the same for an entry with a url like https..., the website is opened in addition?

**Comment by Rookiestyle** [comment]
Closed due to inactivity.

I'll reopen this issue if the open questions are answered.
